// actions/types.js
export const BUSINESS_LIST_REQUEST = 'BUSINESS_LIST_REQUEST';
export const BUSINESS_LIST_SUCCESS = 'BUSINESS_LIST_SUCCESS';
export const BUSINESS_LIST_FAIL = 'BUSINESS_LIST_FAIL';

export const INSERT_BUSINESS_REQUEST = 'INSERT_BUSINESS_REQUEST';
export const INSERT_BUSINESS_SUCCESS = 'INSERT_BUSINESS_SUCCESS';
export const INSERT_BUSINESS_FAIL = 'INSERT_BUSINESS_FAIL';

export const DELETE_BUSINESS_REQUEST = 'DELETE_BUSINESS_REQUEST';
export const DELETE_BUSINESS_SUCCESS = 'DELETE_BUSINESS_SUCCESS';
export const DELETE_BUSINESS_FAIL = 'DELETE_BUSINESS_FAIL';


export const EDIT_BUSINESS_REQUEST = 'EDIT_BUSINESS_REQUEST';
export const EDIT_BUSINESS_SUCCESS = 'EDIT_BUSINESS_SUCCESS';
export const EDIT_BUSINESS_FAIL = 'EDIT_BUSINESS_FAIL';


export const UPDATE_BUSINESS_STATUS_REQUEST = "UPDATE_BUSINESS_STATUS_REQUEST";
export const UPDATE_BUSINESS_STATUS_SUCCESS = "UPDATE_BUSINESS_STATUS_SUCCESS";
export const UPDATE_BUSINESS_STATUS_FAIL = "UPDATE_BUSINESS_STATUS_FAIL";

