export const EXPENSE_CATEGORY_LIST_REQUEST = 'EXPENSE_CATEGORY_LIST_REQUEST'
export const EXPENSE_CATEGORY_LIST_SUCCESS = 'EXPENSE_CATEGORY_LIST_SUCCESS'
export const EXPENSE_CATEGORY_LIST_FAIL = 'EXPENSE_CATEGORY_LIST_FAIL'


export const EXPENSE_CATEGORY_DELETE_REQUEST = 'EXPENSE_CATEGORY_DELETE_REQUEST';
export const EXPENSE_CATEGORY_DELETE_SUCCESS = 'EXPENSE_CATEGORY_DELETE_SUCCESS';
export const EXPENSE_CATEGORY_DELETE_FAIL = 'EXPENSE_CATEGORY_DELETE_FAIL';


export const EXPENSE_CATEGORY_UPDATE_STATUS_REQUEST = "EXPENSE_CATEGORY_UPDATE_STATUS_REQUEST";
export const EXPENSE_CATEGORY_UPDATE_STATUS_SUCCESS = "EXPENSE_CATEGORY_UPDATE_STATUS_SUCCESS";
export const EXPENSE_CATEGORY_UPDATE_STATUS_FAIL = "EXPENSE_CATEGORY_UPDATE_STATUS_FAIL";


export const EXPENSE_CATEGORY_ADD_REQUEST = 'EXPENSE_CATEGORY_ADD_REQUEST';
export const EXPENSE_CATEGORY_ADD_SUCCESS = 'EXPENSE_CATEGORY_ADD_SUCCESS';
export const EXPENSE_CATEGORY_ADD_FAIL = 'EXPENSE_CATEGORY_ADD_FAIL';

export const EXPENSE_CATEGORY_EDIT_REQUEST = 'EXPENSE_CATEGORY_EDIT_REQUEST';
export const EXPENSE_CATEGORY_EDIT_SUCCESS = 'EXPENSE_CATEGORY_EDIT_SUCCESS';
export const EXPENSE_CATEGORY_EDIT_FAIL = 'EXPENSE_CATEGORY_EDIT_FAIL';