export const EXPENSE_LIST_REQUEST = 'EXPENSE_LIST_REQUEST'
export const EXPENSE_LIST_SUCCESS = 'EXPENSE_LIST_SUCCESS'
export const EXPENSE_LIST_FAIL = 'EXPENSE_LIST_FAIL'


export const EXPENSE_INSERT_REQUEST = 'EXPENSE_INSERT_REQUEST';
export const EXPENSE_INSERT_SUCCESS = 'EXPENSE_INSERT_SUCCESS';
export const EXPENSE_INSERT_FAIL = 'EXPENSE_INSERT_FAIL';

export const EXPENSE_DELETE_REQUEST = 'EXPENSE_DELETE_REQUEST';
export const EXPENSE_DELETE_SUCCESS = 'EXPENSE_DELETE_SUCCESS';
export const EXPENSE_DELETE_FAIL = 'EXPENSE_DELETE_FAIL';


export const EXPENSE_EDIT_REQUEST = 'EXPENSE_EDIT_REQUEST';
export const EXPENSE_EDIT_SUCCESS = 'EXPENSE_EDIT_SUCCESS';
export const EXPENSE_EDIT_FAIL = 'EXPENSE_EDIT_FAIL';
