export const GROUP_TYPE_LIST_REQUEST = 'GROUP_TYPE_LIST_REQUEST'
export const GROUP_TYPE_LIST_SUCCESS = 'GROUP_TYPE_LIST_SUCCESS'
export const GROUP_TYPE_LIST_FAIL = 'GROUP_TYPE_LIST_FAIL'


export const GROUP_TYPE_DELETE_REQUEST = 'GROUP_TYPE_DELETE_REQUEST';
export const GROUP_TYPE_DELETE_SUCCESS = 'GROUP_TYPE_DELETE_SUCCESS';
export const GROUP_TYPE_DELETE_FAIL = 'GROUP_TYPE_DELETE_FAIL';


export const GROUP_TYPE_UPDATE_STATUS_REQUEST = "GROUP_TYPE_UPDATE_STATUS_REQUEST";
export const GROUP_TYPE_UPDATE_STATUS_SUCCESS = "GROUP_TYPE_UPDATE_STATUS_SUCCESS";
export const GROUP_TYPE_UPDATE_STATUS_FAIL = "GROUP_TYPE_UPDATE_STATUS_FAIL";


export const GROUP_TYPE_ADD_REQUEST = 'GROUP_TYPE_ADD_REQUEST';
export const GROUP_TYPE_ADD_SUCCESS = 'GROUP_TYPE_ADD_SUCCESS';
export const GROUP_TYPE_ADD_FAIL = 'GROUP_TYPE_ADD_FAIL';

export const GROUP_TYPE_EDIT_REQUEST = 'GROUP_TYPE_EDIT_REQUEST';
export const GROUP_TYPE_EDIT_SUCCESS = 'GROUP_TYPE_EDIT_SUCCESS';
export const GROUP_TYPE_EDIT_FAIL = 'GROUP_TYPE_EDIT_FAIL';