export const INVESTMENT_OFFER_LIST_REQUEST = 'INVESTMENT_OFFER_LIST_REQUEST'
export const INVESTMENT_OFFER_LIST_SUCCESS = 'INVESTMENT_OFFER_LIST_SUCCESS'
export const INVESTMENT_OFFER_LIST_FAIL = 'INVESTMENT_OFFER_LIST_FAIL'



export const INVESTMENT_OFFER_STATUS_UPDATE_REQUEST = "INVESTMENT_OFFER_STATUS_UPDATE_REQUEST";
export const INVESTMENT_OFFER_STATUS_UPDATE_SUCCESS = "INVESTMENT_OFFER_STATUS_UPDATE_SUCCESS";
export const INVESTMENT_OFFER_STATUS_UPDATE_FAIL = "INVESTMENT_OFFER_STATUS_UPDATE_FAIL";



export const INVESTMENT_OFFER_DETAILS_REQUEST = 'INVESTMENT_OFFER_DETAILS_REQUEST'
export const INVESTMENT_OFFER_DETAILS_SUCCESS = 'INVESTMENT_OFFER_DETAILS_SUCCESS'
export const INVESTMENT_OFFER_DETAILS_FAIL = 'INVESTMENT_OFFER_DETAILS_FAIL'


export const INVESTMENT_OFFER_CREATE_REQUEST = 'INVESTMENT_OFFER_CREATE_REQUEST'
export const INVESTMENT_OFFER_CREATE_SUCCESS = 'INVESTMENT_OFFER_CREATE_SUCCESS'
export const INVESTMENT_OFFER_CREATE_FAIL = 'INVESTMENT_OFFER_CREATE_FAIL'


export const INVESTMENT_OFFER_UPDATE_REQUEST = 'INVESTMENT_OFFER_UPDATE_REQUEST'
export const INVESTMENT_OFFER_UPDATE_SUCCESS = 'INVESTMENT_OFFER_UPDATE_SUCCESS'
export const INVESTMENT_OFFER_UPDATE_FAIL = 'INVESTMENT_OFFER_UPDATE_FAIL'


export const INVESTMENT_OFFER_DELETE_REQUEST = 'INVESTMENT_OFFER_DELETE_REQUEST'
export const INVESTMENT_OFFER_DELETE_SUCCESS = 'INVESTMENT_OFFER_DELETE_SUCCESS'
export const INVESTMENT_OFFER_DELETE_FAIL = 'INVESTMENT_OFFER_DELETE_FAIL'

