export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST'
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS'
export const MEMBER_LIST_FAIL = 'MEMBER_LIST_FAIL'


export const MEMBER_DELETE_REQUEST = 'MEMBER_DELETE_REQUEST';
export const MEMBER_DELETE_SUCCESS = 'MEMBER_DELETE_SUCCESS';
export const MEMBER_DELETE_FAIL = 'MEMBER_DELETE_FAIL';


export const MEMBER_STATUS_CHANGE_REQUEST = 'MEMBER_STATUS_CHANGE_REQUEST';
export const MEMBER_STATUS_CHANGE_SUCCESS = 'MEMBER_STATUS_CHANGE_SUCCESS';
export const MEMBER_STATUS_CHANGE_FAIL = 'MEMBER_STATUS_CHANGE_FAIL';


export const MEMBER_ADD_REQUEST = 'MEMBER_ADD_REQUEST';
export const MEMBER_ADD_SUCCESS = 'MEMBER_ADD_SUCCESS';
export const MEMBER_ADD_FAIL = 'MEMBER_ADD_FAIL';

export const MEMBER_EDIT_REQUEST = 'MEMBER_EDIT_REQUEST';
export const MEMBER_EDIT_SUCCESS = 'MEMBER_EDIT_SUCCESS';
export const MEMBER_EDIT_FAIL = 'MEMBER_EDIT_FAIL';


export const MEMBER_UNPAYMENT_LIST_REQUEST = 'MEMBER_UNPAYMENT_LIST_REQUEST';
export const MEMBER_UNPAYMENT_LIST_SUCCESS = 'MEMBER_UNPAYMENT_LIST_SUCCESS';
export const MEMBER_UNPAYMENT_LIST_FAIL = 'MEMBER_UNPAYMENT_LIST_FAIL';
