export const PAYMENT_LIST_REQUEST = 'PAYMENT_LIST_REQUEST'
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS'
export const PAYMENT_LIST_FAIL = 'PAYMENT_LIST_FAIL'


export const PAYMENT_DELETE_REQUEST = 'PAYMENT_DELETE_REQUEST';
export const PAYMENT_DELETE_SUCCESS = 'PAYMENT_DELETE_SUCCESS';
export const PAYMENT_DELETE_FAIL = 'PAYMENT_DELETE_FAIL';


export const PAYMENT_ADD_REQUEST = 'PAYMENT_ADD_REQUEST';
export const PAYMENT_ADD_SUCCESS = 'PAYMENT_ADD_SUCCESS';
export const PAYMENT_ADD_FAIL = 'PAYMENT_ADD_FAIL';

export const PAYMENT_EDIT_REQUEST = 'PAYMENT_EDIT_REQUEST';
export const PAYMENT_EDIT_SUCCESS = 'PAYMENT_EDIT_SUCCESS';
export const PAYMENT_EDIT_FAIL = 'PAYMENT_EDIT_FAIL';