export const ROLE_PERMISSION_LIST_REQUEST = 'ROLE_PERMISSION_LIST_REQUEST'
export const ROLE_PERMISSION_LIST_SUCCESS = 'ROLE_PERMISSION_LIST_SUCCESS'
export const ROLE_PERMISSION_LIST_FAIL = 'ROLE_PERMISSION_LIST_FAIL'


export const PERMISSION_LIST_REQUEST = 'PERMISSION_LIST_REQUEST'
export const PERMISSION_LIST_SUCCESS = 'PERMISSION_LIST_SUCCESS'
export const PERMISSION_LIST_FAIL = 'PERMISSION_LIST_FAIL'

export const ROLE_PERMISSION_ADD_REQUEST = 'ROLE_PERMISSION_ADD_REQUEST';
export const ROLE_PERMISSION_ADD_SUCCESS = 'ROLE_PERMISSION_ADD_SUCCESS';
export const ROLE_PERMISSION_ADD_FAIL = 'ROLE_PERMISSION_ADD_FAIL';


export const ROLE_PERMISSION_EDIT_REQUEST = 'ROLE_PERMISSION_EDIT_REQUEST';
export const ROLE_PERMISSION_EDIT_SUCCESS = 'ROLE_PERMISSION_EDIT_SUCCESS';
export const ROLE_PERMISSION_EDIT_FAIL = 'ROLE_PERMISSION_EDIT_FAIL';


export const ROLE_PERMISSION_DELETE_REQUEST = 'ROLE_PERMISSION_DELETE_REQUEST';
export const ROLE_PERMISSION_DELETE_SUCCESS = 'ROLE_PERMISSION_DELETE_SUCCESS';
export const ROLE_PERMISSION_DELETE_FAIL = 'ROLE_PERMISSION_DELETE_FAIL';
